name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: [self-hosted, Linux, AWS]
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Get CodeArtifact authorization token
        uses: Brightspace/codeartifact-actions/get-authorization-token@main
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      - name: Add CodeArtifact npm registry
        uses: Brightspace/codeartifact-actions/npm/add-registry@main
        with:
          auth-token: ${{env.CODEARTIFACT_AUTH_TOKEN}}
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.D2L_RELEASE_TOKEN }}
          MINOR_RELEASE_WITH_LMS: true
          NPM: true
      - name: Get new git HEAD
        id: git
        run: echo "head=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
