name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.D2L_RELEASE_TOKEN }}
          MINOR_RELEASE_WITH_LMS: true
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
